from __future__ import annotations
import json
from scripts._common import save_json

def main():
    report={'architectures':[{'name':'LLM reads table text','numeric_accuracy':None},{'name':'Deterministic XBRL query','numeric_accuracy':'generated by evaluate_financial.py'}],'note':'No LLM-table accuracy is claimed until the local model benchmark is run.'};save_json('reports/ablations/structured_data_ablation.json',report);print(json.dumps(report,indent=2))
if __name__=='__main__':main()
